### ISSUE TITLE
pageStart and pageEnd type

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocds_documentation_extension#1]
Currently the permitted types for ```pageStart``` and ```pageEnd``` are ```string``` and null```.

Should this be changed to ```number``` and ```null``` so that we can do tighter validation and so that consuming applications can use the field more easily?

**Comment by timgdavies** [comment]
As the description states "This should refer to the printed page number, not the page number reported by software applications." then there are cases where the printed page number might be something like 'XII' or 'Appendix 1' or '§1-2' or other such strings - we need to allow strings as well as numbers.

**Comment by duncandewhurst** [comment]
Makes sense - thanks Tim.
